### ISSUE TITLE
More Specific Selectors

### ISSUE THREAD

**Issue by cyouh95** [karolisracas/prj-rev-bwfs-dasmoto#4]
I noticed each of your 3 section `div` containers also have a class of "[item](https://github.com/karolisracas/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L10)". You could use this as part of your selector here to be more specific on which elements to select and style:
```css
.item h2 {
  font-size: 32px;
  color: white;
}
```
https://github.com/karolisracas/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L15-L18
